### ISSUE TITLE
error occured when i click the [+ new graph] button!

### ISSUE THREAD

**Issue by limng06** [findyourmagic/dber#8]
![image](https://user-images.githubusercontent.com/3937109/179194469-c8880e00-6eb6-48ce-b8a4-9e59f61f5b78.png)
Unhandled Runtime Error
DataCloneError: Failed to execute 'add' on 'IDBObjectStore': PointerEvent object could not be cloned.
 DataCloneError: Failed to execute 'add' on 'IDBObjectStore': PointerEvent object could not be cloned.

Source
pages\graphs\index.js (30:11) @ _callee$

  28 | id,
  29 | name: 'Untitled graph',
> 30 | box: {
     |   ^
  31 |     x: 0,
  32 |     y: 0,
  33 |     w: global.innerWidth,
Call Stack
addGraph
pages\graphs\index.js (45:15)
_callee$
pages\graphs\index.js (30:11)
addGraph
pages\graphs\index.js (45:15)
Show collapsed frames

**Comment by limng06** [comment]
console output:

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
event - compiled client and server successfully in 3.3s (129 modules)
wait  - compiling / (client and server)...
wait  - compiling...
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 3.7s (810 modules)
wait  - compiling /graphs (client and server)...
wait  - compiling...
event - compiled client and server successfully in 1501 ms (1142 modules)
Warning: Failed prop type: Invalid prop `in` of type `string` supplied to `CSSTransition`, expected `boolean`.
    at CSSTransition (D:\Repository\dber\node_modules\react-transition-group\cjs\CSSTransition.js:118:35)
    at Modal (D:\Repository\dber\node_modules\@arco-design\web-react\lib\Modal\modal.js:108:42)
    at ImportModal (webpack-internal:///./components/import_modal.js:46:28)
    at div
    at ListNav (webpack-internal:///./components/list_nav.js:28:98)
    at Home (webpack-internal:///./pages/graphs/index.js:79:90)
    at MyApp (webpack-internal:///./pages/_app.js:14:18)
    at StyleRegistry (D:\Repository\dber\node_modules\styled-jsx\dist\index\index.js:671:34)
    at FlushEffectContainer (D:\Repository\dber\node_modules\next\dist\server\render.js:428:37)
    at AppContainer (D:\Repository\dber\node_modules\next\dist\server\render.js:443:29)
    at AppContainerWithIsomorphicFiberStructure (D:\Repository\dber\node_modules\next\dist\server\render.js:474:57)
    at div
    at Body (D:\Repository\dber\node_modules\next\dist\server\render.js:738:21)

**Comment by xtexChooser** [comment]
+1

**Comment by findyourmagic** [comment]
@limng06 Thanks for this.
The first add graph error has been fixed.
May the second console output  caused by arco design. I'll find a solution later.

**Comment by findyourmagic** [comment]
The console output error has been fixed too.
